import { useState, useEffect } from "react";

export function useFormOptions() {
  const [districts, setDistricts] = useState([
    "Ahmednagar",
    "Akola",
    "Amravati",
    "Aurangabad",
    "Beed",
    "Bhandara",
    "Buldhana",
    "Chandrapur",
    "Dhule",
    "Gadchiroli",
    "Gondia",
    "Hingoli",
    "Jalgaon",
    "Jalna",
    "Kolhapur",
    "Latur",
    "Mumbai City",
    "Mumbai Suburban",
    "Nagpur",
    "Nanded",
    "Nandurbar",
    "Nashik",
    "Osmanabad",
    "Palghar",
    "Parbhani",
    "Pune",
    "Raigad",
    "Ratnagiri",
    "Sangli",
    "Satara",
    "Sindhudurg",
    "Solapur",
    "Thane",
    "Wardha",
    "Washim",
    "Yavatmal",
    "Anantapur",
    "Chittoor",
    "East Godavari",
    "Guntur",
    "Kadapa",
    "Krishna",
    "Kurnool",
    "Prakasam",
    "Srikakulam",
    "Visakhapatnam",
    "Vizianagaram",
    "West Godavari",
    "Baksa",
    "Barpeta",
    "Biswanath",
    "Bongaigaon",
    "Cachar",
    "Charaideo",
    "Chirang",
    "Darrang",
    "Dhemaji",
    "Dhubri",
    "Dibrugarh",
    "Goalpara",
    "Golaghat",
    "Hailakandi",
    "Hojai",
    "Jorhat",
    "Kamrup",
    "Kamrup Metropolitan",
    "Karbi Anglong",
    "Karimganj",
    "Kokrajhar",
    "Lakhimpur",
    "Majuli",
    "Morigaon",
    "Nagaon",
    "Nalbari",
    "Sivasagar",
    "Sonitpur",
    "South Salmara-Mankachar",
    "Tinsukia",
    "Udalguri",
    "West Karbi Anglong",
  ]);
  const [talukas, setTalukas] = useState([  "Achalpur", "Ahmadpur", "Aheri", "Ahmednagar", "Ajra", "Akola", "Akole", "Akkalkot", 
    "Saswad", "Satana", "Satara", "Savner", "Sawantwadi", "Seloo", "Shahade", "Shahapur", 
    "Shahuwadi", "Shegaon", "Shevgaon", "Shipur", "Shirala", "Shirol", "Shirpur-Warvade", 
    "Shirur", "Shirur Anantpal", "Shrigonda", "Shrirampur", "Shrivardhan", "Sillod", "Sindewahi", 
    "Sindkhed Raja", "Sindhudurg", "Sindkheda", "Singnapur", "Sinner", "Sironcha", "Soegaon", 
    "Solapur North", "Solapur South", "Sonpeth", "Surgana", "Talegaon Dabhade", "Taloda", 
    "Tasgaon", "Thane", "Tirora", "Trimbakeshwar", "Tuljapur", "Tumsar", "Udgir", "Umarkhed", 
    "Umarga", "Umred", "Uran", "Vada", "Vaduj", "Vaibhavvadi", "Vaijapur", "Vasai", "Velhe", 
    "Vengurla", "Vikramgad", "Vita", "Wada", "Wai", "Walwa", "Wani", "Wardha", "Warora", 
    "Washim", "Yaval", "Yavatmal", "Yeola", "Zari-Jamani"]);
  const [states, setStates] = useState([
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
  ]);
  const [cities, setCities] = useState([    "Mumbai",
    "Pune",
    "Nagpur",
    "Thane",
    "Nashik",
    "Aurangabad",
    "Solapur",
    "Kolhapur",
    "Amravati",
    "Navi Mumbai",
    "Sangli",
    "Malegaon",
    "Akola",
    "Latur",
    "Dhule",
    "Ahmednagar",
    "Chandrapur",
    "Parbhani",
    "Jalgaon",
    "Bhiwandi"]);
  const [municipalCorporations, setMunicipalCorporations] = useState([   "Brihanmumbai Municipal Corporation",
    "Bhiwandi-Nizampur Municipal Corporation",
    "Nagpur Municipal Corporation",
    "Pune Municipal Corporation",
    "Thane Municipal Corporation",
    "Pimpri-Chinchwad Municipal Corporation",
    "Nashik Municipal Corporation",
    "Kalyan Dombivli Municipal Corporation",
    "Vasai-Virar City Municipal Corporation",
    "Navi Mumbai Municipal Corporation",
    "Aurangabad Municipal Corporation",
    "Solapur Municipal Corporation",
    "Kolhapur Municipal Corporation",
    "Sangli-Miraj & Kupwad Municipal Corporation",
    "Jalgaon City Municipal Corporation",
    "Akola Municipal Corporation",
    "Amravati Municipal Corporation",
    "Latur City Municipal Corporation",
    "Nanded-Waghala Municipal Corporation",
    "Parbhani Municipal Corporation",
    "Panvel Municipal Corporation",
    "Mira Bhaindar Municipal Corporation",
    "Ulhasnagar Municipal Corporation",
    "Chandrapur City Municipal Corporation",
    "Dhule Municipal Corporation",
    "Malegaon Municipal Corporation",
    "Ichalkaranji Municipal Corporation",
    "Jalna Municipal Corporation"]);
  const [constituencies, setConstituencies] = useState([    "Akkalkuwa",
    "Shahada",
    "Nandurbar",
    "Nawapur",
    "Sakri",
    "Shirpur",
    "Dhule Rural",
    "Dhule City",
    "Sindhkheda",
    "Malegaon (Central)",
    "Malegaon (Outer)",
    "Baglan",
    "Jalgaon City",
    "Jalgaon Rural",
    "Amalner",
    "Erandol",
    "Chalisgaon",
    "Pachora",
    "Raver",
    "Chopda",
    "Bhusawal",
    "Jamner",
    "Muktainagar",
    "Malkapur",
    "Buldhana",
    "Chikhli",
    "Sindhkhed Raja",
    "Mehkar",
    "Khamgaon",
    "Akot",
    "Balapur",
    "Akola West",
    "Akola East",
    "Murtizapur",
    "Risod",
    "Badnera",
    "Amravati",
    "Teosa",
    "Daryapur",
    "Melghat",
    "Achalpur",
    "Dhamangaon Railway",
    "Morshi",
    "Arvi",
    "Deoli",
    "Hinganghat",
    "Wardha",
    "Katol",
    "Savner",
    "Hingna",
    "Umred",
    "Kamthi",
    "Nagpur South West",
    "Nagpur South",
    "Nagpur East",
    "Nagpur Central",
    "Nagpur West",
    "Nagpur North",
    "Tumsar",
    "Bhandara",
    "Sakoli",
    "Gondia",
    "Amgaon",
    "Armori",
    "Gadchiroli",
    "Bramhapuri",
    "Rajura",
    "Chandrapur",
    "Ballarpur",
    "Warora",
    "Wani",
    "Arni",
    "Umarkhed",
    "Kinwat",
    "Hadgaon",
    "Bhokar",
    "Nanded North",
    "Nanded South",
    "Naigaon",
    "Deglur",
    "Mukhed",
    "Jintur",
    "Gangakhed",
    "Pathri",
    "Partur",
    "Badnapur",
    "Bhokardan",
    "Sillod",
    "Pholambari",
    "Paithan",
    "Kannad",
    "Aurangabad (Central)",
    "Aurangabad (West)",
    "Aurangabad (East)",
    "Gangapur",
    "Vaijapur",
    "Dindori",
    "Nandgaon",
    "Kalwan",
    "Chandwad",
    "Yevla",
    "Niphad",
    "Sinnar",
    "Palghar",
    "Dahanu",
    "Vekramgrth"]);

//   useEffect(() => {
//     // Fetch districts
//     fetch("/https://your-website.com/data/indian-districts.json")
//       .then((response) => response.json())
//       .then((data) => setDistricts(data))
//       .catch((error) => console.error("Error fetching districts:", error));

//     // Fetch talukas
//     fetch("/api/talukas")
//       .then((response) => response.json())
//       .then((data) => setTalukas(data))
//       .catch((error) => console.error("Error fetching talukas:", error));

//     // Fetch states
//     fetch("/api/states")
//       .then((response) => response.json())
//       .then((data) => setStates(data))
//       .catch((error) => console.error("Error fetching states:", error));

//     // Fetch cities
//     fetch("/api/cities")
//       .then((response) => response.json())
//       .then((data) => setCities(data))
//       .catch((error) => console.error("Error fetching cities:", error));

//     // Fetch municipal corporations
//     fetch("/api/municipal-corporations")
//       .then((response) => response.json())
//       .then((data) => setMunicipalCorporations(data))
//       .catch((error) =>
//         console.error("Error fetching municipal corporations:", error)
//       );

//     // Fetch constituencies
//     fetch("/api/constituencies")
//       .then((response) => response.json())
//       .then((data) => setConstituencies(data))
//       .catch((error) => console.error("Error fetching constituencies:", error));
//   }, []);

  return {
    districts,
    talukas,
    states,
    cities,
    municipalCorporations,
    constituencies,
  };
}
